<?php

ob_start();

require "functions.php";

session_checker_delfin();

// wipes it, if it exists already
if (isset($_SESSION['targetUsersArray'])) {
    unset($_SESSION['targetUsersArray']);
}




$selectedList = "list_A";   // this is usefull

$grabbedUsers = [];

$db = db_connect_delfin();

// $query = "SELECT id, allocation, nom, nom2, fonction, adresse1, adresse2, allocationSpeciale, email, nomCouponReponse, letter_required FROM Users WHERE $selectedList = ?";
$query = "SELECT * FROM Users WHERE $selectedList = ?";     //? I just grab everything for possible future expansions
$stmt = $db->prepare($query);
$listTrue = 1;
$stmt->bind_param("i", $listTrue);
$stmt->execute();
$result = $stmt->get_result();

$stmt->close();

db_close_delfin($db);


include 'header.html';

// 
?>

<div class="table_wrapper">
    <table>
        <caption>
            Edit Users Only in List A
        </caption>
        <thead>
            <tr>
                <th>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
        </thead>
        <tbody>


            <tr class="duplicateUser">
                <th>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
            <th>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
            <th>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
            <th>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
            <th>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
            <th>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>
            <tr>
                <th>HELLO</th>
                <th>HELLO</th>
                <th>HELLO</th>
            </tr>



        </tbody>
    </table>
</div>


