FROM php:8.4.8-apache
                            #! must match the exact version as specified in compose.yaml

# # install docker's php extension : mysqli
# RUN docker-php-ext-install mysqli

# install docker's php extension : mysqli & pdo_mysql
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

# Increase max upload size to 20MB
RUN echo "upload_max_filesize=20M" > /usr/local/etc/php/conf.d/upload_large_dumps.ini && \
    echo "post_max_size=20M" >> /usr/local/etc/php/conf.d/upload_large_dumps.ini

RUN echo "display_startup_errors=Off" > /usr/local/etc/php/conf.d/custom.ini && \
    echo "log_errors=On" >> /usr/local/etc/php/conf.d/custom.ini && \
    echo "error_log=/var/log/php_errors.log" >> /usr/local/etc/php/conf.d/custom.ini



# composer is currently handled with the batch file since we're in Windows
# RUN composer install


# other stuff

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y libzip-dev git && \
    docker-php-ext-install zip

# RUN apt-get update && apt-get install -y libreoffice libreoffice-writer

# Libre Office needs this to work
RUN apt-get update && apt-get install -y \
    libreoffice \
    libreoffice-writer \
    libreoffice-core \
    libreoffice-common \
    libreoffice-calc \
    libreoffice-impress \
    fonts-dejavu \
    && rm -rf /var/lib/apt/lists/*


# custom apache config
RUN a2enmod rewrite
COPY ./httpd.conf /etc/apache2/conf-enabled/httpd.conf


#? yeah I struggle with getting composer to work properly while using a docker volume (also in that case composer.json and .lock should be in this directory)

# # install composer

# RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
#     php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
#     php -r "unlink('composer-setup.php');"
# # RUN mv composer.phar /usr/local/bin/composer




# NOTES:

# https://packagist.org/

